# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false

    sass: %assetic.sass.bin%
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        less:
            node: %node_path%
            node_paths: %node_paths%
            apply_to: "\.less$"
        scss: ~
